apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }} 
  namespace: default
  labels:
    app: project-ecr 
spec:
  selector:
    app: project-ecr 
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  type: LoadBalancer